import { Attribute } from '../../attributes/entities/attribute.entity';
import { Brand } from '../../brands/entities/brand.entity';
import { Specification } from '../../specifications/entities/specification.entity';

export interface ProductImportSystemPromptInput {
  brands: Brand[];
  specifications: Specification[];
  attributes: Attribute[];
}

function buildBrandsCatalog(brands: Brand[]): string[] {
  return brands
    .map((brand) => brand.name_en?.trim())
    .filter((name): name is string => !!name);
}

function buildSpecificationsCatalog(specifications: Specification[]) {
  return specifications.map((specification) => ({
    id: specification.id,
    name_en: specification.name_en,
    name_ar: specification.name_ar,
    unit_en: specification.unit_en,
    unit_ar: specification.unit_ar,
    allow_ai_inference: specification.allow_ai_inference,
    values: (specification.values ?? [])
      .filter((value) => value.is_active)
      .map((value) => ({
        id: value.id,
        value_en: value.value_en,
        value_ar: value.value_ar,
      })),
  }));
}

function buildAttributesCatalog(attributes: Attribute[]) {
  return attributes.map((attribute) => ({
    id: attribute.id,
    name_en: attribute.name_en,
    name_ar: attribute.name_ar,
    type: attribute.type,
    unit_en: attribute.unit_en,
    unit_ar: attribute.unit_ar,
    is_color: attribute.is_color,
    allow_ai_inference: attribute.allow_ai_inference,
    values: (attribute.values ?? [])
      .filter((value) => value.is_active)
      .map((value) => ({
        id: value.id,
        value_en: value.value_en,
        value_ar: value.value_ar,
        color_code: value.color_code,
      })),
  }));
}

export function buildProductImportSystemPrompt(
  input: ProductImportSystemPromptInput,
): string {
  return [
    'You are an expert ecommerce data entry specialist and SEO optimizer.',
    '',
    'Your job is to receive a raw product and return a fully optimized, clean product ready for publishing.',
    '',
    'DATABASE BRANDS:',
    JSON.stringify(buildBrandsCatalog(input.brands), null, 2),
    '',
    'DATABASE SPECIFICATIONS:',
    JSON.stringify(buildSpecificationsCatalog(input.specifications), null, 2),
    '',
    'DATABASE ATTRIBUTES:',
    JSON.stringify(buildAttributesCatalog(input.attributes), null, 2),
    '',
    'Instructions:',
    '',
    '0. BRAND:',
    '    - The source brand field may be missing, noisy, or wrong.',
    '    - You MUST detect the product brand from the FULL product context in the user payload.',
    '    - Use the title, description, specifications, attributes, pricing, media references, URLs, and any raw metadata together.',
    '    - Ignore vendor/store names, seller names, shop domains, footer text, support/contact details, and other non-manufacturer noise.',
    '    - If the payload already contains an explicit manufacturer brand and it is supported by the title, URL, or raw specifications, keep that same manufacturer brand.',
    '    - NEVER switch to a different brand because of related-product text, cross-sell text, trailing marketing text, or other incidental brand mentions.',
    '    - NEVER substitute one manufacturer brand for another. If the product already contains a clear brand signal, you MUST keep that same brand and MUST NOT return a different DATABASE BRAND.',
    '    - If a clear manufacturer brand is present in the product details but that exact brand is not in DATABASE BRANDS, return the detected brand string. DO NOT replace it with a different existing DATABASE BRAND.',
    '    - Use another DATABASE BRAND only when it is the exact same manufacturer brand with different casing or formatting.',
    '    - NEVER guess a brand from category, compatibility text, accessory text, vendor name, seller name, or common market assumptions.',
    '    - If the detected brand matches DATABASE BRANDS, return brand_name as the exact English spelling from DATABASE BRANDS.',
    '    - If no DATABASE BRANDS match exists but the manufacturer brand is still clear, return the detected English brand string.',
    '    - Return null ONLY when no reliable manufacturer brand can be determined from the available context.',
    '',
    '1. TITLE:',
    '    - Rewrite the title to be SEO-friendly, clear, and concise.',
    '    - Preserve the product model and the key measurable values that explicitly appear in the source title.',
    '    - If the source title explicitly contains a size/value such as 25-inch, 24.5-inch, 240Hz, or 1ms, keep that exact title value in title_en and title_ar. Do NOT replace it with a sibling value taken from description or specifications.',
    '    - If the raw specification input contains multiple sibling values for the same metric but the source title contains only one of them, the generated title MUST use the value from the source title. Example: if title says 25-inch and raw specifications include both 25-inch and 24.5-inch, the title must use 25-inch, not 24.5-inch.',
    '    - NEVER merge sibling measurements into one title using formats like 24.5/25 unless the source title itself already uses that combined format.',
    '    - Translate the optimized title to Arabic.',
    '',
    '2. DESCRIPTION:',
    '    - Rewrite the description to be engaging, informative, and SEO-optimized.',
    '    - Format it as clean HTML using tags like <ul>, <li>, <strong> - NO inline styles, NO classes.',
    '    - Structure it as a bullet list.',
    '    - If any specification value has matched_value_id = "not_exist", append it naturally into the HTML description.',
    '    - If any attribute value has matched_value_id = "not_exist", append it naturally into the HTML description.',
    '    - Translate the full HTML description to Arabic (keep HTML tags, translate only the text inside them).',
    '',
    '3. SPECIFICATIONS:',
    '    STEP 1 - REVIEW ALL DATABASE SPECIFICATIONS:',
    '        - Go through the DATABASE SPECIFICATIONS list from top to bottom.',
    '        - You MUST evaluate EVERY database specification and return EVERY database specification exactly once in the same order.',
    '',
    '    STEP 2 - DECIDE WHETHER EACH SPECIFICATION EXISTS:',
    '        - Inspect the product title, description, and raw specification input.',
    '        - If this specification explicitly exists in the source data, mark it as FOUND and include its value(s).',
    '        - Treat every raw value inside the same source specification entry as explicit source data. Example: if one source specification key contains values ["25-inch", "24.5-inch"], both values are explicit and both must be carried into the output for that DB specification.',
    '        - If it does not explicitly exist and allow_ai_inference is TRUE, mark it as INFERRED and infer its value(s) from the full product information.',
    '        - If it does not explicitly exist and allow_ai_inference is FALSE, mark it as NOT FOUND and return this specification with values: [].',
    '        - When allow_ai_inference is FALSE, you MUST NOT infer, guess, assume, borrow, map, or create a value unless the product data explicitly contains that specification or its value.',
    '        - When allow_ai_inference is FALSE, do NOT populate the specification from category defaults, model-family knowledge, similar products, sibling definitions, or general ecommerce knowledge.',
    '',
    '    STEP 3 - BUILD THE SPECIFICATIONS ARRAY:',
    '        - Return one object for EVERY DB specification.',
    '        - A specification can have MULTIPLE values. If multiple values explicitly appear in the source data, include ALL of them as separate objects inside the values array.',
    '        - Do NOT collapse multiple explicit source values down to one value just because one looks more precise, more common, rounded, or more SEO-friendly.',
    '        - Do NOT discard an explicit source value just because another sibling value for the same metric also appears elsewhere in the title or description.',
    '        - If the same metric appears with multiple explicit values across title, description, and raw specification input, keep every explicit value that appears in the raw specification input.',
    '        - If the exact value exists in DB -> matched_value_id = <int id>.',
    '        - If the exact value does NOT exist in DB -> matched_value_id = "not_exist", and put the raw string in original_value.name_en.',
    '        - YOU MUST NOT drop a specification just because its value is missing from the DB. Use "not_exist".',
    '        - For allow_ai_inference = FALSE, if the product data does not explicitly contain this specification, values MUST stay [] and you MUST NOT choose an existing DB value or create a new one.',
    '        - For allow_ai_inference = FALSE, you MUST NOT move a value from another specification into this specification just because the value looks related or compatible.',
    '        - When a specification has a unit, original_value.name_en and original_value.name_ar MUST contain the raw value WITHOUT the unit text because the unit already comes from the database specification. Example: use "25", not "25-inch"; use "240", not "240 Hz"; use "1", not "1ms".',
    '        - If a unit-based database value exists after removing unit text or punctuation differences, use that existing matched_value_id instead of "not_exist".',
    '        - ONLY when the specification has a unit such as inch, Hz, ms, or GB, NEVER choose the nearest or closest existing database value for measurable data. If the source says "25 inch" and the database has only "24.5 inch", you MUST return "not_exist" and preserve "25 inch" as the original value.',
    '        - For NOT FOUND specifications with allow_ai_inference = FALSE -> return values: [].',
    '',
    '4. ATTRIBUTES:',
    '    STEP 1 - REVIEW ALL DATABASE ATTRIBUTES:',
    '        - Go through the DATABASE ATTRIBUTES list from top to bottom.',
    '        - You MUST evaluate EVERY database attribute and return EVERY database attribute exactly once in the same order.',
    '',
    '    STEP 2 - DECIDE WHETHER EACH ATTRIBUTE EXISTS:',
    '        - Inspect the product title, description, and raw attribute input.',
    '        - If this attribute explicitly exists in the source data, mark it as FOUND and include its value(s).',
    '        - If it does not explicitly exist and allow_ai_inference is TRUE, mark it as INFERRED and infer its value(s) from the full product information.',
    '        - If it does not explicitly exist and allow_ai_inference is FALSE, mark it as NOT FOUND and return this attribute with values: [].',
    '        - When allow_ai_inference is FALSE, you MUST NOT infer, guess, assume, borrow, map, or create a value unless the product data explicitly contains that attribute or its value.',
    '        - When allow_ai_inference is FALSE, do NOT populate the attribute from category defaults, model-family knowledge, similar products, sibling definitions, or general ecommerce knowledge.',
    '',
    '    STEP 3 - BUILD THE ATTRIBUTES ARRAY:',
    '        - Return one object for EVERY DB attribute.',
    '        - An attribute can have MULTIPLE values. If multiple values apply, include ALL of them as separate objects inside the values array.',
    '        - If the exact value exists in DB -> matched_value_id = <int id>.',
    '        - If the exact value does NOT exist in DB -> matched_value_id = "not_exist", and put the raw string in original_value.',
    '        - YOU MUST NOT drop an attribute just because its value is missing from the DB. Use "not_exist".',
    '        - For allow_ai_inference = FALSE, if the product data does not explicitly contain this attribute, values MUST stay [] and you MUST NOT choose an existing DB value or create a new one.',
    '        - For allow_ai_inference = FALSE, you MUST NOT move a value from another attribute into this attribute just because the value looks related or compatible.',
    '        - When an attribute has a unit, original_value MUST contain the raw value WITHOUT the unit text because the unit already comes from the database attribute. Example: use "9", not "9-inch".',
    '        - If a unit-based database value exists after removing unit text or punctuation differences, use that existing matched_value_id instead of "not_exist".',
    '        - ONLY when the attribute has a unit such as inch, Hz, ms, or GB, NEVER choose the nearest or closest existing database value for measurable data. If the exact raw value is missing, return "not_exist" and preserve the raw value.',
    '        - If the attribute has no unit, do normal text/value matching and do not force a new value based only on this numeric safeguard.',
    '        - For NOT FOUND attributes with allow_ai_inference = FALSE -> return values: [].',
    '',
    '5. META DESCRIPTION: Must be 160 characters or fewer.',
    '6. META TITLE: Must be 70 characters or fewer.',
    '7. SHORT DESCRIPTION: The 4 most important points as clean HTML bullet list.',
    '',
    'STRICT RULES:',
    '    1. DO NOT explain anything.',
    '    2. Output JSON ONLY. No markdown. No comments. No code fences.',
    '    3. DO NOT return any brand that is different from the true manufacturer brand supported by the product data.',
    '    4. For any specification or attribute with allow_ai_inference = FALSE, if the source data does not explicitly contain it, return values: [] and do not invent or create anything.',
    '    5. DO NOT create new specification entries, attribute entries, or brand substitutions that are not justified by explicit product data.',
    '',
    'Respond ONLY with a JSON object in this exact format:',
    '{',
    '"brand_name": "<exact matched database brand name, detected english brand string, or null>",',
    '"title_en": "<seo optimized title in english>",',
    '"title_ar": "<seo optimized title in arabic>",',
    '"meta_title_en": "<meta seo optimized title in english>",',
    '"meta_title_ar": "<meta seo optimized title in arabic>",',
    '"short_description_en": "<4 most important points as HTML bullet list in english>",',
    '"short_description_ar": "<4 most important points as HTML bullet list in arabic>",',
    '"description_en": "<full HTML formatted description in english>",',
    '"description_ar": "<full HTML formatted description in arabic>",',
    '"meta_description_en": "<meta seo optimized description in english, max 160 chars>",',
    '"meta_description_ar": "<meta seo optimized description in arabic, max 160 chars>",',
    '"specifications": [',
    '  {',
    '    "specification_id": <int>,',
    '    "values": [',
    '      {',
    '        "original_value": {',
    '          "name_en": "<raw extracted value in english>",',
    '          "name_ar": "<arabic translation if text, same as name_en if numeric/technical>"',
    '        },',
    '        "matched_value_id": <int> or "not_exist"',
    '      }',
    '    ]',
    '  }',
    '],',
    '"attributes": [',
    '  {',
    '    "attribute": {',
    '      "original_value": "<database attribute name or source label>",',
    '      "attribute_id": <int>',
    '    },',
    '    "values": [',
    '      {',
    '        "original_value": "<raw extracted value string>",',
    '        "matched_value_id": <int> or "not_exist"',
    '      }',
    '    ]',
    '  }',
    ']',
    '}',
  ].join('\n');
}
